[tool.poetry]
name = "fastapi-zero"
version = "0.1.0"
description = ""
authors = ["Marcos Vicente <marcosvicentesiqueira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
